### ISSUE TITLE
The Android App Is Not Working

### ISSUE THREAD

**Issue by servusdei** [cyberboysumanjay/UdemySales#1]
I have Downloaded The Android App And It Is Not Working.

**Comment by cyberboysumanjay** [comment]
Please explain the issue with the problem that you're facing.
I just tried the app and it's working fine.

Also let me know the specifications of the device on which you tried to install it.

**Comment by servusdei** [comment]
> Please explain the issue with the problem that you're facing.
> I just tried the app and it's working fine.
> 
> Also let me know the specifications of the device on which you tried to install it.

I am Using Samsung A2 Core And When I try To Open Application Its Only Loading I am Trying That For Several Minutes

**Comment by cyberboysumanjay** [comment]
> > Please explain the issue with the problem that you're facing.
> > I just tried the app and it's working fine.
> > Also let me know the specifications of the device on which you tried to install it.
> 
> I am Using Samsung A2 Core And When I try To Open Application Its Only Loading I am Trying That For Several Minutes

It takes around 10-12 seconds to load at startup. Are you waiting for it to load completely?
Are you using any kind of VPN or behind 1.1.1.1 Service?

It should not happen with your device as you're using Android Oreo+ Version I suppose.

**Comment by servusdei** [comment]
> > > Please explain the issue with the problem that you're facing.
> > > I just tried the app and it's working fine.
> > > Also let me know the specifications of the device on which you tried to install it.
> > 
> > 
> > I am Using Samsung A2 Core And When I try To Open Application Its Only Loading I am Trying That For Several Minutes
> 
> It takes around 10-12 seconds to load at startup. Are you waiting for it to load completely?
> Are you using any kind of VPN or behind 1.1.1.1 Service?
> 
> It should not happen with your device as you're using Android Oreo+ Version I suppose.

Thanks For Your Response I am Using a Vpn Now I have Closed That and its working Fine

**Comment by cyberboysumanjay** [comment]
Glad to hear that it worked :smiley:
