### ISSUE TITLE
Images Loading Issue

### ISSUE THREAD

**Issue by ArunBalajiR** [cyberboysumanjay/UdemySales#3]
In early days . This app works well in android 10. But now there is a issue in loading images for courses.Some times the app stuck on loading screen.When terminate app and re run it.it works well.

![image](https://user-images.githubusercontent.com/53110175/98077483-51b9f080-1e96-11eb-9ab8-860125dd3e58.png)

**Comment by cyberboysumanjay** [comment]
Hey,
Thanks for flagging this issue. 
It was a server side side and now it should be fixed 😃
Try it and let me know if it occurs again
